<a href="https://colab.research.google.com/github/codegeek03/Machine-Learning/blob/main/Baap_Level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
# univariate convlstm example
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import ConvLSTM2D
from keras.models import load_model
from keras.utils import to_categorical

In [ ]:
!git clone https://github.com/ArnabSarkar007/GC-Project.git

Cloning into 'GC-Project'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 2), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 569.96 KiB | 4.22 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Error downloading object: test_x.csv (cefc0ce): Smudge error: Error downloading test_x.csv (cefc0ce09c1c373330c522e8c253462cd5a7234b8886ddda542742f5c46fcf2c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /content/GC-Project/.git/lfs/logs/20240301T165933.533055634.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: test_x.csv: smudge filter lfs failed
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'



In [ ]:
df = pd.read_csv("/content/GC-Project/train_x.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/GC-Project/train_x.csv'

In [ ]:
y = pd.read_csv('/content/GC-Project/train_y.csv')

In [ ]:
df

In [ ]:
df.drop(columns="time", inplace=True)

NameError: name 'df' is not defined

In [ ]:
df.head(20)

NameError: name 'df' is not defined

In [ ]:
df.describe()

NameError: name 'df' is not defined

In [ ]:
df.corr().plot()

NameError: name 'df' is not defined

In [ ]:
import seaborn as sns

In [ ]:
df.set_index('id', inplace=True)


NameError: name 'df' is not defined

In [ ]:
df.head(10)

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
id                                                                           
0    0.4337   0.7431   0.9390   0.7541   0.9035   0.7943   0.2622   0.5901   
0    0.7859   0.1925   0.9024   0.8108   0.2016   0.9649   0.2445   0.8934   
0    0.0512   0.9633   0.1423   0.8404   0.6654   0.4348   0.5751   0.8067   
0    0.0413   0.1588   0.1675   0.0971   0.2918   0.1970   0.0971   0.2039   
0    0.7042   0.4724   0.3901   0.2793   0.2522   0.1933   0.2694   0.4110   
0    0.9538   0.3029   0.4227   0.7774   0.5194   0.7531   0.4816   0.9918   
0    0.6729   0.9906   0.8604   0.2969   0.8278   0.4840   0.2507   0.0795   
0    0.3945   0.4753   0.6420   0.9227   0.8885   0.1002   0.5443   0.8279   
0    0.7368   0.8174   0.8750   0.1230   0.3970   0.7676   0.5175   0.8211   
0    0.6752   0.1698   0.6974   0.1273   0.5090   0.3354   0.8128   0.2753   

    sensor9  sensor10  ...  sensor16  sensor17  sensor18  sensor19  sensor20  \
id                     ...                                                     
0    0.7558    0.2675  ...    0.5696    0.6407    0.7027    0.7163    0.9954   
0    0.9039    0.9474  ...    0.4259    0.7456    0.5750    0.7947    0.4663   
0    0.3372    0.3346  ...    0.4753    0.5449    0.8531    0.6337    0.8807   
0    0.3392    0.8863  ...    0.7959    0.5306    0.3109    0.2726    0.3298   
0    0.3608    0.3153  ...    0.2474    0.5711    0.5686    0.6575    0.1447   
0    0.0920    0.7097  ...    0.2433    0.2040    0.1013    0.6044    0.9570   
0    0.9068    0.9769  ...    0.1682    0.7322    0.9347    0.0961    0.2847   
0    0.9093    0.8412  ...    0.0176    0.2317    0.8063    0.4249    0.7711   
0    0.3583    0.3890  ...    0.7746    0.0908    0.7100    0.7641    0.7748   
0    0.1591    0.9358  ...    0.7912    0.1517    0.6923    0.7245    0.6380   

    sensor21  sensor22  sensor23  sensor24  sensor25  
id                                                    
0     0.8303    0.1641    0.7893    0.7533    0.2925  
0     0.4303    0.3643    0.0558    0.1330    0.0295  
0     0.2560    0.0597    0.5751    0.7797    0.8544  
0     0.4658    0.7479    0.8747    0.2677    0.3816  
0     0.5774    0.4022    0.6753    0.8371    0.6748  
0     0.8958    0.8006    0.5282    0.4132    0.4582  
0     0.4782    0.2882    0.4375    0.5795    0.8926  
0     0.4558    0.5419    0.4521    0.3392    0.6380  
0     0.9589    0.7818    0.9553    0.7653    0.1555  
0     0.0089    0.4479    0.6776    0.7189    0.2121  

[10 rows x 25 columns]

In [ ]:
y

Unnamed: 0  state
0               0    1.0
1               1    2.0
2               2    3.0
3               3    1.0
4               4    1.0
...           ...    ...
49995       49995    0.0
49996       49996    3.0
49997       49997    1.0
49998       49998    0.0
49999       49999    1.0

[50000 rows x 2 columns]

In [ ]:
y.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
y

state
0        1.0
1        2.0
2        3.0
3        1.0
4        1.0
...      ...
49995    0.0
49996    3.0
49997    1.0
49998    0.0
49999    1.0

[50000 rows x 1 columns]

In [ ]:
y.values

array([[1.],
       [2.],
       [3.],
       ...,
       [1.],
       [0.],
       [1.]])

In [ ]:
n_steps = 10 # considering 10 time steps
n_features = 25 # number of sensors

In [ ]:
df.shape

(500000, 25)

In [ ]:
X = df.values

In [ ]:
X

array([[0.4337, 0.7431, 0.939 , ..., 0.7893, 0.7533, 0.2925],
       [0.7859, 0.1925, 0.9024, ..., 0.0558, 0.133 , 0.0295],
       [0.0512, 0.9633, 0.1423, ..., 0.5751, 0.7797, 0.8544],
       ...,
       [0.5622, 0.7094, 0.1205, ..., 0.4906, 0.7756, 0.5428],
       [0.3565, 0.4717, 0.6521, ..., 0.6706, 0.1297, 0.8826],
       [0.7871, 0.2163, 0.1643, ..., 0.4489, 0.4848, 0.5125]])

In [ ]:
X.shape

(500000, 25)

In [ ]:
y

state
0        1.0
1        2.0
2        3.0
3        1.0
4        1.0
...      ...
49995    0.0
49996    3.0
49997    1.0
49998    0.0
49999    1.0

[50000 rows x 1 columns]

In [ ]:
y.shape

(50000, 1)

In [ ]:
tempx = X

In [ ]:
tempx

array([[0.4337, 0.7431, 0.939 , ..., 0.7893, 0.7533, 0.2925],
       [0.7859, 0.1925, 0.9024, ..., 0.0558, 0.133 , 0.0295],
       [0.0512, 0.9633, 0.1423, ..., 0.5751, 0.7797, 0.8544],
       ...,
       [0.5622, 0.7094, 0.1205, ..., 0.4906, 0.7756, 0.5428],
       [0.3565, 0.4717, 0.6521, ..., 0.6706, 0.1297, 0.8826],
       [0.7871, 0.2163, 0.1643, ..., 0.4489, 0.4848, 0.5125]])

In [ ]:
tempx.shape[0]

500000

In [ ]:
tempx[0]

array([0.4337, 0.7431, 0.939 , 0.7541, 0.9035, 0.7943, 0.2622, 0.5901,
       0.7558, 0.2675, 0.4097, 0.1722, 0.42  , 0.7719, 0.8553, 0.5696,
       0.6407, 0.7027, 0.7163, 0.9954, 0.8303, 0.1641, 0.7893, 0.7533,
       0.2925])

In [ ]:
tempx_reshaped = tempx.reshape((50000,n_steps,n_features))

In [ ]:
tempx_reshaped[0]

array([[0.4337, 0.7431, 0.939 , 0.7541, 0.9035, 0.7943, 0.2622, 0.5901,
        0.7558, 0.2675, 0.4097, 0.1722, 0.42  , 0.7719, 0.8553, 0.5696,
        0.6407, 0.7027, 0.7163, 0.9954, 0.8303, 0.1641, 0.7893, 0.7533,
        0.2925],
       [0.7859, 0.1925, 0.9024, 0.8108, 0.2016, 0.9649, 0.2445, 0.8934,
        0.9039, 0.9474, 0.7457, 0.6983, 0.2097, 0.3358, 0.4028, 0.4259,
        0.7456, 0.575 , 0.7947, 0.4663, 0.4303, 0.3643, 0.0558, 0.133 ,
        0.0295],
       [0.0512, 0.9633, 0.1423, 0.8404, 0.6654, 0.4348, 0.5751, 0.8067,
        0.3372, 0.3346, 0.957 , 0.3021, 0.5279, 0.8505, 0.2061, 0.4753,
        0.5449, 0.8531, 0.6337, 0.8807, 0.256 , 0.0597, 0.5751, 0.7797,
        0.8544],
       [0.0413, 0.1588, 0.1675, 0.0971, 0.2918, 0.197 , 0.0971, 0.2039,
        0.3392, 0.8863, 0.8181, 0.7741, 0.4613, 0.5736, 0.0601, 0.7959,
        0.5306, 0.3109, 0.2726, 0.3298, 0.4658, 0.7479, 0.8747, 0.2677,
        0.3816],
       [0.7042, 0.4724, 0.3901, 0.2793, 0.2522, 0.1933, 0.2694, 0.41

model = Sequential()
model.add(LSTM(300, input_shape=(n_steps,n_features), return_sequences=True))
model.add(LSTM(300))
model.add(Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
y_train_one_hot = to_categorical(y, 4)
y_train_one_hot

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)

model.fit(tempx_reshaped,y_train_one_hot, epochs=100)

model.save("lstm_model_new1.h5")

In [ ]:
test_x = pd.read_csv('/content/GC-Project/test_x.csv')

In [ ]:
test_x

id  time  sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  \
0     50000     1   0.3786   0.7031   0.0734   0.0492   0.8328   0.9048   
1     50000     2   0.0871   0.3716   0.1444   0.4848   0.8051   0.6569   
2     50000     3   0.7733   0.3273   0.0397   0.2026   0.7231   0.4640   
3     50000     4   0.4817   0.6624   0.3319   0.7669   0.4364   0.1332   
4     50000     5   0.0100   0.8568   0.5611   0.0171   0.2108   0.1046   
...     ...   ...      ...      ...      ...      ...      ...      ...   
9995  50999     6   0.5563   0.0273   0.4050   0.0035   0.8710   0.3533   
9996  50999     7   0.0702   0.7417   0.8893   0.3615   0.6888   0.5658   
9997  50999     8   0.1935   0.8997   0.3039   0.9757   0.5910   0.5253   
9998  50999     9   0.2718   0.7367   0.6270   0.8462   0.4284   0.4649   
9999  50999    10   0.0469   0.0085   0.3151   0.5123   0.2128   0.2023   

      sensor7  sensor8  ...  sensor16  sensor17  sensor18  sensor19  sensor20  \
0      0.7850   0.9979  ...    0.6897    0.9130    0.5681    0.0129    0.4369   
1      0.8121   0.5083  ...    0.6067    0.1750    0.3267    0.1499    0.4746   
2      0.2385   0.0435  ...    0.2943    0.5956    0.4769    0.8894    0.8833   
3      0.4890   0.7637  ...    0.4996    0.2766    0.4083    0.9838    0.5823   
4      0.4475   0.8220  ...    0.2412    0.4066    0.2261    0.1200    0.8346   
...       ...      ...  ...       ...       ...       ...       ...       ...   
9995   0.8382   0.5167  ...    0.6842    0.8704    0.1593    0.1494    0.6192   
9996   0.9178   0.6649  ...    0.1328    0.3443    0.7526    0.0556    0.8064   
9997   0.0459   0.3327  ...    0.0930    0.1710    0.2240    0.8013    0.1723   
9998   0.0397   0.3281  ...    0.3151    0.1197    0.4840    0.5379    0.7549   
9999   0.7841   0.9495  ...    0.5829    0.4715    0.2034    0.5418    0.6209   

      sensor21  sensor22  sensor23  sensor24  sensor25  
0       0.5533    0.2384    0.4805    0.3959    0.4756  
1       0.2572    0.7884    0.3364    0.8252    0.8013  
2       0.0786    0.4448    0.0071    0.4052    0.5436  
3       0.3014    0.2781    0.1267    0.7782    0.1162  
4       0.3691    0.5683    0.1112    0.7261    0.5521  
...        ...       ...       ...       ...       ...  
9995    0.2081    0.4659    0.8334    0.6913    0.2214  
9996    0.5836    0.7398    0.6256    0.6917    0.8379  
9997    0.4518    0.9341    0.5166    0.2043    0.9384  
9998    0.3839    0.6309    0.8746    0.6079    0.4322  
9999    0.7071    0.8569    0.7406    0.1911    0.3436  

[10000 rows x 27 columns]

In [ ]:
test_x.set_index('id', inplace=True)

In [ ]:
test_x

time  sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  \
id                                                                           
50000     1   0.3786   0.7031   0.0734   0.0492   0.8328   0.9048   0.7850   
50000     2   0.0871   0.3716   0.1444   0.4848   0.8051   0.6569   0.8121   
50000     3   0.7733   0.3273   0.0397   0.2026   0.7231   0.4640   0.2385   
50000     4   0.4817   0.6624   0.3319   0.7669   0.4364   0.1332   0.4890   
50000     5   0.0100   0.8568   0.5611   0.0171   0.2108   0.1046   0.4475   
...     ...      ...      ...      ...      ...      ...      ...      ...   
50999     6   0.5563   0.0273   0.4050   0.0035   0.8710   0.3533   0.8382   
50999     7   0.0702   0.7417   0.8893   0.3615   0.6888   0.5658   0.9178   
50999     8   0.1935   0.8997   0.3039   0.9757   0.5910   0.5253   0.0459   
50999     9   0.2718   0.7367   0.6270   0.8462   0.4284   0.4649   0.0397   
50999    10   0.0469   0.0085   0.3151   0.5123   0.2128   0.2023   0.7841   

       sensor8  sensor9  ...  sensor16  sensor17  sensor18  sensor19  \
id                       ...                                           
50000   0.9979   0.0691  ...    0.6897    0.9130    0.5681    0.0129   
50000   0.5083   0.6790  ...    0.6067    0.1750    0.3267    0.1499   
50000   0.0435   0.6084  ...    0.2943    0.5956    0.4769    0.8894   
50000   0.7637   0.1217  ...    0.4996    0.2766    0.4083    0.9838   
50000   0.8220   0.4366  ...    0.2412    0.4066    0.2261    0.1200   
...        ...      ...  ...       ...       ...       ...       ...   
50999   0.5167   0.9549  ...    0.6842    0.8704    0.1593    0.1494   
50999   0.6649   0.9708  ...    0.1328    0.3443    0.7526    0.0556   
50999   0.3327   0.3633  ...    0.0930    0.1710    0.2240    0.8013   
50999   0.3281   0.7176  ...    0.3151    0.1197    0.4840    0.5379   
50999   0.9495   0.8293  ...    0.5829    0.4715    0.2034    0.5418   

       sensor20  sensor21  sensor22  sensor23  sensor24  sensor25  
id                                                                 
50000    0.4369    0.5533    0.2384    0.4805    0.3959    0.4756  
50000    0.4746    0.2572    0.7884    0.3364    0.8252    0.8013  
50000    0.8833    0.0786    0.4448    0.0071    0.4052    0.5436  
50000    0.5823    0.3014    0.2781    0.1267    0.7782    0.1162  
50000    0.8346    0.3691    0.5683    0.1112    0.7261    0.5521  
...         ...       ...       ...       ...       ...       ...  
50999    0.6192    0.2081    0.4659    0.8334    0.6913    0.2214  
50999    0.8064    0.5836    0.7398    0.6256    0.6917    0.8379  
50999    0.1723    0.4518    0.9341    0.5166    0.2043    0.9384  
50999    0.7549    0.3839    0.6309    0.8746    0.6079    0.4322  
50999    0.6209    0.7071    0.8569    0.7406    0.1911    0.3436  

[10000 rows x 26 columns]

In [ ]:
test_x.drop(columns=['time'], inplace=True)

In [ ]:
test_x

sensor1  sensor2  sensor3  sensor4  sensor5  sensor6  sensor7  sensor8  \
id                                                                              
50000   0.3786   0.7031   0.0734   0.0492   0.8328   0.9048   0.7850   0.9979   
50000   0.0871   0.3716   0.1444   0.4848   0.8051   0.6569   0.8121   0.5083   
50000   0.7733   0.3273   0.0397   0.2026   0.7231   0.4640   0.2385   0.0435   
50000   0.4817   0.6624   0.3319   0.7669   0.4364   0.1332   0.4890   0.7637   
50000   0.0100   0.8568   0.5611   0.0171   0.2108   0.1046   0.4475   0.8220   
...        ...      ...      ...      ...      ...      ...      ...      ...   
50999   0.5563   0.0273   0.4050   0.0035   0.8710   0.3533   0.8382   0.5167   
50999   0.0702   0.7417   0.8893   0.3615   0.6888   0.5658   0.9178   0.6649   
50999   0.1935   0.8997   0.3039   0.9757   0.5910   0.5253   0.0459   0.3327   
50999   0.2718   0.7367   0.6270   0.8462   0.4284   0.4649   0.0397   0.3281   
50999   0.0469   0.0085   0.3151   0.5123   0.2128   0.2023   0.7841   0.9495   

       sensor9  sensor10  ...  sensor16  sensor17  sensor18  sensor19  \
id                        ...                                           
50000   0.0691    0.0115  ...    0.6897    0.9130    0.5681    0.0129   
50000   0.6790    0.8613  ...    0.6067    0.1750    0.3267    0.1499   
50000   0.6084    0.6720  ...    0.2943    0.5956    0.4769    0.8894   
50000   0.1217    0.6403  ...    0.4996    0.2766    0.4083    0.9838   
50000   0.4366    0.1632  ...    0.2412    0.4066    0.2261    0.1200   
...        ...       ...  ...       ...       ...       ...       ...   
50999   0.9549    0.4244  ...    0.6842    0.8704    0.1593    0.1494   
50999   0.9708    0.8701  ...    0.1328    0.3443    0.7526    0.0556   
50999   0.3633    0.3562  ...    0.0930    0.1710    0.2240    0.8013   
50999   0.7176    0.9642  ...    0.3151    0.1197    0.4840    0.5379   
50999   0.8293    0.6303  ...    0.5829    0.4715    0.2034    0.5418   

       sensor20  sensor21  sensor22  sensor23  sensor24  sensor25  
id                                                                 
50000    0.4369    0.5533    0.2384    0.4805    0.3959    0.4756  
50000    0.4746    0.2572    0.7884    0.3364    0.8252    0.8013  
50000    0.8833    0.0786    0.4448    0.0071    0.4052    0.5436  
50000    0.5823    0.3014    0.2781    0.1267    0.7782    0.1162  
50000    0.8346    0.3691    0.5683    0.1112    0.7261    0.5521  
...         ...       ...       ...       ...       ...       ...  
50999    0.6192    0.2081    0.4659    0.8334    0.6913    0.2214  
50999    0.8064    0.5836    0.7398    0.6256    0.6917    0.8379  
50999    0.1723    0.4518    0.9341    0.5166    0.2043    0.9384  
50999    0.7549    0.3839    0.6309    0.8746    0.6079    0.4322  
50999    0.6209    0.7071    0.8569    0.7406    0.1911    0.3436  

[10000 rows x 25 columns]

In [ ]:
test_x_values = test_x.values

In [ ]:
testx_reshaped = test_x_values.reshape((1000,n_steps,n_features))

In [ ]:
testx_reshaped.shape

(1000, 10, 25)

preds = model.predict(testx_reshaped)

In [ ]:
preds

array([[0.23783796, 0.35172874, 0.25437066, 0.15606263],
       [0.31398347, 0.34933355, 0.17727078, 0.1594122 ],
       [0.31117207, 0.31976438, 0.19404146, 0.17502211],
       ...,
       [0.11266947, 0.08614921, 0.3720576 , 0.4291238 ],
       [0.23862521, 0.3284294 , 0.25458068, 0.17836474],
       [0.3204906 , 0.16513133, 0.16412553, 0.3502525 ]], dtype=float32)

In [ ]:
len(preds)

1000

In [ ]:
pred_cls = []
for i in range(0,len(preds)):
  pred_cls.append(np.argmax(preds[i]))

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten

# Define the modelm
model = Sequential()

# Convolutional layer
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(10, 25)))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layer
model.add(Flatten())

# Reshape to fit the LSTM input shape
model.add(tf.keras.layers.Reshape((4, 64)))  # Adjust the shape as per your requirements

# LSTM layer
model.add(LSTM(50, return_sequences=True))
model.add(LSTM(50))

# Output layer
model.add(Dense(4, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the summary of the model
model.summary()

In [ ]:
model.fit(tempx_reshaped[:40000], y_encoded[:40000], epochs = 50)

NameError: name 'y_encoded' is not defined

In [ ]:
model.evaluate(tempx_reshaped[40000:], y_encoded[40000:])

NameError: name 'y_encoded' is not defined

In [ ]:
pip install scikit-optimize

In [ ]:
from tensorflow.keras.utils import to_categorical
y_encoded = to_categorical(y)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

# Define the model function for grid search
def create_model(filters, kernel_size, pool_size, lstm_units1, lstm_units2):
    model = Sequential()
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, activation='relu', input_shape=(10, 25)))
    model.add(MaxPooling1D(pool_size=pool_size))
    model.add(Flatten())
    model.add(tf.keras.layers.Reshape((4, filters)))  # Adjust the shape as per your requirements
    model.add(LSTM(lstm_units1, return_sequences=True))
    model.add(LSTM(lstm_units2))
    model.add(Dense(4, activation='softmax'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

from sklearn.model_selection import train_test_split


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:

# Load your data (assuming tempx_reshaped and y_encoded are defined)
# tempx_reshaped, y_encoded = load_data()

# Split the data into training and validation sets
tempx_train, tempx_val, y_train, y_val = train_test_split(tempx_reshaped, y_encoded, test_size=0.2, random_state=42)

# Grid Search
param_grid = {
    'filters': [32, 64],
    'kernel_size': [3, 5],
    'pool_size': [2, 3],
    'lstm_units1': [50, 64],
    'lstm_units2': [50, 64]
}

model = tf.keras.wrappers.scikit_learn.KerasClassifier(build_fn=create_model, epochs=50, batch_size=32, verbose=0)
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy')
grid_result = grid.fit(tempx_train, y_train)

# Print the best parameters from the grid search
print("Best parameters from grid search: ", grid_result.best_params_)

# Bayesian Optimization
opt_model = tf.keras.wrappers.scikit_learn.KerasClassifier(build_fn=create_model, epochs=50, batch_size=32, verbose=0)
opt = BayesSearchCV(opt_model, param_grid, n_iter=10, cv=3, scoring='accuracy')
opt_result = opt.fit(tempx_train, y_train)

# Print the best parameters from Bayesian optimization
print("Best parameters from Bayesian optimization: ", opt_result.best_params_)

# Train the best model with early stopping
best_model = opt_result.best_estimator_.model
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
best_model.fit(tempx_train, y_train, epochs=50, validation_data=(tempx_val, y_val), callbacks=[early_stopping])

# Evaluate the best model on the test set
test_loss, test_accuracy = best_model.evaluate(tempx_reshaped[40000:], y_encoded[40000:])
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

AttributeError: module 'tensorflow.keras' has no attribute 'wrappers'

In [ ]:
!pip install scikeras
from scikeras.wrappers import KerasClassifier

**Grid and Bayseian Optimization Combined **

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from tensorflow.keras.callbacks import EarlyStopping
# from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
# from tensorflow.keras.wrappers import KerasClassifier
from scikeras.wrappers import KerasClassifier

# Assuming you have your features (X) and labels (y) defined
# For example:
# X = your_features
# y = your_labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model function for grid search
def create_model(filters, kernel_size, pool_size, lstm_units1, lstm_units2):
    model = Sequential()
    model.add(Conv1D(filters=filters, kernel_size=kernel_size, activation='relu', input_shape=(10, 25)))
    model.add(MaxPooling1D(pool_size=pool_size))
    model.add(Flatten())
    model.add(tf.keras.layers.Reshape((4, filters)))
    model.add(LSTM(lstm_units1, return_sequences=True))
    model.add(LSTM(lstm_units2))
    model.add(Dense(4, activation='softmax'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Grid Search
param_grid = {
    'filters': [32, 64],
    'kernel_size': [3, 5],
    'pool_size': [2, 3],
    'lstm_units1': [50, 64],
    'lstm_units2': [50, 64]
}

model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=32, verbose=0)
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring='accuracy')
grid_result = grid.fit(X_train, y_train)

# Print the best parameters from the grid search
print("Best parameters from grid search: ", grid_result.best_params_)

# Bayesian Optimization
opt_model = KerasClassifier(build_fn=create_model, epochs=50, batch_size=32, verbose=0)
opt = BayesSearchCV(opt_model, param_grid, n_iter=10, cv=3, scoring='accuracy')
opt_result = opt.fit(X_train, y_train)

# Print the best parameters from Bayesian optimization
print("Best parameters from Bayesian optimization: ", opt_result.best_params_)

# Train the best model with early stopping
best_model = opt_result.best_estimator_.model
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
best_model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Evaluate the best model on the test set
test_loss, test_accuracy = best_model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)


ModuleNotFoundError: No module named 'skopt'