In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.keras as keras

In [2]:
text_file_path = 'train.txt'

with open(text_file_path, 'r', encoding='latin-1') as file:
    text_data = file.read()

# Display a sample of the |text
print(text_data[:300])

Certainly! Here's a longer sample story for you:

---

In the quaint town of Willowbrook, where cobblestone streets intertwined with ivy-covered cottages, there lived a young woman named Isabella. Willowbrook was a place where time seemed to stand still, and the townsfolk embraced the charm of a byg


In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

tokenizer.fit_on_texts(text_data)

tokenizer.word_index

{'e': 1,
 't': 2,
 'a': 3,
 'o': 4,
 'r': 5,
 's': 6,
 'n': 7,
 'i': 8,
 'h': 9,
 'd': 10,
 'l': 11,
 'w': 12,
 'c': 13,
 'g': 14,
 'b': 15,
 'f': 16,
 'u': 17,
 'y': 18,
 'm': 19,
 'p': 20,
 'v': 21,
 'k': 22,
 "'": 23,
 'j': 24,
 'q': 25,
 'x': 26,
 '\x97': 27}

In [4]:
tokenizer.fit_on_texts([text_data])
tokenizer.word_index

{'e': 1,
 't': 2,
 'a': 3,
 'o': 4,
 'r': 5,
 's': 6,
 'n': 7,
 'i': 8,
 'h': 9,
 'd': 10,
 'l': 11,
 'w': 12,
 'c': 13,
 'g': 14,
 'the': 15,
 'b': 16,
 'f': 17,
 'u': 18,
 'y': 19,
 'm': 20,
 'p': 21,
 'v': 22,
 'of': 23,
 'and': 24,
 'k': 25,
 'to': 26,
 'that': 27,
 'she': 28,
 'with': 29,
 'woods': 30,
 'isabella': 31,
 'whispering': 32,
 'her': 33,
 "'": 34,
 'in': 35,
 'j': 36,
 'as': 37,
 'where': 38,
 'forest': 39,
 'willowbrook': 40,
 'book': 41,
 'ancient': 42,
 'into': 43,
 'was': 44,
 'through': 45,
 'tales': 46,
 "isabella's": 47,
 'by': 48,
 'trees': 49,
 'on': 50,
 'journey': 51,
 'heart': 52,
 'became': 53,
 'q': 54,
 'x': 55,
 'time': 56,
 'embraced': 57,
 'ordinary': 58,
 'hidden': 59,
 'discovered': 60,
 'air': 61,
 'mystical': 62,
 'creatures': 63,
 'its': 64,
 'between': 65,
 'reality': 66,
 'who': 67,
 'guardian': 68,
 'magic': 69,
 'for': 70,
 'you': 71,
 'quaint': 72,
 'town': 73,
 'cobblestone': 74,
 'streets': 75,
 'intertwined': 76,
 'ivy': 77,
 'covered': 7

In [5]:
len(tokenizer.word_index)

324

In [6]:
input_seq = []

for sentence in text_data.split('\n'):
    tok_sen = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tok_sen)):
        n_gram = tok_sen[:i+1]
        input_seq.append(n_gram)


In [7]:
input_seq

[[113, 114],
 [113, 114, 3],
 [113, 114, 3, 115],
 [113, 114, 3, 115, 116],
 [113, 114, 3, 115, 116, 117],
 [113, 114, 3, 115, 116, 117, 70],
 [113, 114, 3, 115, 116, 117, 70, 71],
 [35, 15],
 [35, 15, 72],
 [35, 15, 72, 73],
 [35, 15, 72, 73, 23],
 [35, 15, 72, 73, 23, 40],
 [35, 15, 72, 73, 23, 40, 38],
 [35, 15, 72, 73, 23, 40, 38, 74],
 [35, 15, 72, 73, 23, 40, 38, 74, 75],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78, 79],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78, 79, 118],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78, 79, 118, 119],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78, 79, 118, 119, 3],
 [35, 15, 72, 73, 23, 40, 38, 74, 75, 76, 29, 77, 78, 79, 118, 119, 3, 120],
 [35,
  15,
  72,
  73,
  23,
  40,
  38,
  74,
  75,
  76,
  29,
  77,
  78,
  79

In [8]:
max_len=max([len(x) for x in input_seq])

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences = pad_sequences(input_seq, maxlen=max_len, padding='pre')

In [10]:
padded_sequences

array([[  0,   0,   0, ...,   0, 113, 114],
       [  0,   0,   0, ..., 113, 114,   3],
       [  0,   0,   0, ..., 114,   3, 115],
       ...,
       [  0,   0,   0, ...,  51,  45,  15],
       [  0,   0,   0, ...,  45,  15,  32],
       [  0,   0,   0, ...,  15,  32,  30]], dtype=int32)

In [11]:
X=padded_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0, 113],
       [  0,   0,   0, ...,   0, 113, 114],
       [  0,   0,   0, ..., 113, 114,   3],
       ...,
       [  0,   0,   0, ..., 324,  51,  45],
       [  0,   0,   0, ...,  51,  45,  15],
       [  0,   0,   0, ...,  45,  15,  32]], dtype=int32)

In [12]:
y=padded_sequences[:,-1]
y

array([114,   3, 115, 116, 117,  70,  71,  15,  72,  73,  23,  40,  38,
        74,  75,  76,  29,  77,  78,  79, 118, 119,   3, 120, 121, 122,
        31,  40,  44,   3, 123,  38,  56,  80,  26, 124,  81,  24,  15,
        82,  57,  15, 125,  23,   3, 126, 127,  44,   3, 128, 129, 130,
        70,  83,  27,  84,  15,  58,  28, 131,  33,  85, 132,  45,  15,
        86,  87, 133, 134, 135,  88,  29,  89,  46,  24,  59, 136, 137,
        44,  35,  90, 138, 139, 140,  23,  15,  87,  27,  31,  60,  91,
        92, 141, 142,  41,  29,   3, 143,  93, 144,  41, 145, 146,  23,
        15,  32,  30, 147,  15, 148,  23, 149,  24,  94, 150,  26, 151,
       152,  47, 153, 154, 155,  15, 156, 157,  37,  28, 158,  15,  41,
        26, 159, 160,  88,  29, 161,  83,  23,   3,  95,  39,  27, 162,
       163, 164,  15,  86, 165,  48,  15,  46,  23, 167,  49,  96, 168,
        24,  15, 169,  32,  30,  31, 170,  26, 171,  50,   3,  51,  27,
       172, 173,  33, 174, 175, 176,  29,  15,  42,  41,  24,   

In [13]:
X.shape

(642, 65)

In [14]:
y.shape

(642,)

In [15]:
#one hot encoding for multi_class classification
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [16]:
y.shape

(642, 325)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Assuming vocab_size is the size of your vocabulary, embed_size is the desired embedding size,
# and max_len is the maximum sequence length
vocab_size = 325 # Replace with your actual vocabulary size
embed_size = 100   # Replace with your desired embedding size
max_len = 65       # Replace with your desired maximum sequence length

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embed_size, input_length=max_len))
model.add(LSTM(150))
model.add(Dense(vocab_size, activation='softmax'))


In [18]:
model.compile(loss='categorical_crossentropy', optimizer='adam' )

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 65, 100)           32500     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 325)               49075     
                                                                 
Total params: 232175 (906.93 KB)
Trainable params: 232175 (906.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
 model.fit(X,y,epochs=100)

Epoch 1/100
21/21 [==============================] - 8s 224ms/step - loss: 5.6435
Epoch 2/100
21/21 [==============================] - 5s 259ms/step - loss: 5.2139
Epoch 3/100
21/21 [==============================] - 5s 212ms/step - loss: 5.0856
Epoch 4/100
21/21 [==============================] - 5s 230ms/step - loss: 5.0411
Epoch 5/100
21/21 [==============================] - 3s 153ms/step - loss: 5.0224
Epoch 6/100
21/21 [==============================] - 3s 145ms/step - loss: 4.9951
Epoch 7/100
21/21 [==============================] - 3s 129ms/step - loss: 4.9659
Epoch 8/100
21/21 [==============================] - 3s 155ms/step - loss: 4.9137
Epoch 9/100
21/21 [==============================] - 2s 112ms/step - loss: 4.8534
Epoch 10/100
21/21 [==============================] - 2s 111ms/step - loss: 4.7553
Epoch 11/100
21/21 [==============================] - 2s 113ms/step - loss: 4.6365
Epoch 12/100
21/21 [==============================] - 3s 156ms/step - loss: 4.4978
Epoch 13/100


In [21]:
text = input("Enter a text")

for j in range(0,3):
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_token_text = pad_sequences([token_text], maxlen=max_len, padding='pre')
    prediction = model.predict(padded_token_text)
    predicted_index = np.argmax(prediction)
    for word,index in tokenizer.word_index.items():
      if index==predicted_index:
        text=text+" "+word
        print(text)


KeyboardInterrupt: Interrupted by user

In [22]:
import pickle

In [23]:
filename='train_model.sav'
pickle.dump(model,open(filename,'wb'))

In [24]:
loaded_model=pickle.load(open(filename,'rb'))

In [25]:
filename='tokeniser.sav'
pickle.dump(model,open(filename,'wb'))